### ISSUE TITLE
không cài được rnbase

### ISSUE THREAD

**Issue by hoangtrunnam** [danghungtb26/rn-base#5]
![image](https://user-images.githubusercontent.com/57910461/227708352-c82a11be-415e-417b-9ebc-4ae3a6217167.png)

+ em là 1 người mới chuyển qua RN và đang tìm kiếm 1 thư viện xây dựng UI nhanh chóng. e thấy example của a có mấy cái Box, Text khá là hay, nhưng khi muốn install package thì lại gặp lỗi như trên ạ. a có thể chỉ e cách cài hoặc là viết lại docs cho những người mới dễ tiếp cận được ko ạ

**Comment by danghungtb26** [comment]
@hoangtrunnam  em cài băng cách này:
```
    yarn add @rn-base/core
    yarn add @rn-base/element
    yarn add @rn-base/splash
    yarn add @rn-base/eslint-config
```
